name: End-to-End Test
on:
  push:
    branches: [ integration ]
  pull_request:
    branches: [ integration ]
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: maven:3.5-jdk-8
    services:
      hub:
        image: selenium/standalone-firefox:4.1.2-20220217
        ports:
          - 4444:4444
          - 7900:7900
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: integration

      - name: Run all tests
        run: mvn test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: target/surefire-reports/junitreports/*.xml

      - name: Code coverage
        uses: codecov/codecov-action@v2
